### ISSUE TITLE
v3.0.0 RoutingError: Unknown file extension ".ts" for...

### ISSUE THREAD

**Issue by DiV666** [oas-tools/oas-tools#335]
I migrate from 2.1.8 to 3.0.0 but i can't load .ts router files, Can not be loaded in this new version?

I am modifying the configuration of v2.1.8
```
{
    controllers: `${__dirname}/routes`,
    customLogger: logger,
    customErrorHandling: true,
    strict: true,
    validator: true,
    docs: {
        apiDocs: '/definition',
        apiDocsPrefix: '/tools',
        swaggerUi: '/swagger-ui',
        swaggerUiPrefix: '/tools'
    },
    oasSecurity: false
}
```

A la nueva versión v3.0.0
```
{
    oasFile: `${__dirname}/config/swagger/definition.yaml`,
    logger: {
        customLogger: logger
    },
    middleware: {
        swagger: {
            path: '/tools/swagger-ui',
        }, 
        router: {
            controllers: `${__dirname}/routes`
        }
    }
}
```

**Comment by alesancor1** [comment]
The router dynamically imports the controllers, but .ts files cannot be directly imported into Javascript. Typescript is compiled, meaning that in order to get your controllers working, you first need to compile your TS project before running.

**Comment by DiV666** [comment]
But the strategy of importing the controllers in v3 is different from the previous version, right?

Do you mean I can't use .ts files for controllers at development if I update?

**Comment by alesancor1** [comment]
The v3 uses dynamic imports `import( )` to load controllers whereas the previous versions used `require( )`. However TS files can't be directly imported in JS doesn't matter which approach you are using. Check [this stack overflow answer](https://stackoverflow.com/questions/54410351/import-typescript-file-in-javascript). Did you manage to initialize v2 with ts files? If so please provide a minimal example so I can reproduce it

**Comment by DiV666** [comment]
I have created a very simple example in typescript with both versions in case you want to try it: https://github.com/DiV666/oas-tools-v3-ts-controllers

**Comment by alesancor1** [comment]
Thanks for the example. After some time I managed to find a workaround to your problem. The problem comes with OAS Tools being declared as an ESM module `"type": "module"` in `package.json`, you are compiling your TS as CommonJS.

In order for your server to work, you need to change it to ESM. In the example you provided, I made the following changes:

```ts
// api-v3.ts

import http from 'http';
import express from 'express';
// @ts-ignore
import * as oasTools from "@oas-tools/core"; // Change oas-tools require to ESM import

const api = express();
api.use(express.json());
api.use(
    express.urlencoded({
        extended: true
    })
);

// Remove __dirname as ESM does not support it. OAS Tools v3 support relative paths based on process.cwd()
const oasConfig = {
    oasFile: `./swagger-v3.yaml`,
    middleware: {
        swagger: {
            path: '/tools/swagger-ui',
        }, 
        router: {
            controllers: `./src/controllers`
        }
    }
}

/* OAS Tools initialization has no changes */
```

In your tsconfig.json change `"module": "commonjs"` to `"module": "es6"` and add `"moduleResolution: "node"` to your compiler options.

Finally add `"type": "module"` to your package json and change the `watch-v3` script to `ts-node-esm ./api-v3.ts`

After making those changes, your server should initialize correctly.

This behaviour will be fixed in future versions since I am planning to migrate the whole ecosystem to TS, avoiding all kind of ESM/CommonJS incompatibility issues, but for now this is the solution I found. I'll try to migrate to TS asap if I see more people with similar issues. Let me know if this workaround solved your problem.

**Note:** I noticed you are using ts-node-dev, however it seems to not be working correctly with ESM. It returns ` Error: Must use import to load ES Module` when trying to run `tsnd -r esm --poll --respawn --no-notify ./api-v3.ts` (having esm package installed previously). There is an open issue about this topic in the ts-node-dev repo: [issue](https://github.com/wclr/ts-node-dev/issues/212)

**Comment by DiV666** [comment]
Thank you very much for your effort

In the repo I did not install the exact versions of the typescript packages and in my project there are these, which I have to update to be able to launch ts-node-esm:
- ts-node: 10.0.0
- ts-node-dev: 1.1.6
- typescript: 4.2.4

I have tried to update and use your workaround without success, I have other dependencies that I have to modify and it would take too much effort

Esperaré a que podáis migrar la librería a typescript o vuelva la compatibilidad con commonjs :)

**Comment by jagdish-176** [comment]
@DiV666 can you try to add `.js` at end of controller in swagger.yaml, for me `oas-tool/core` tries to pick up `apps.d.ts` instead of apps.js from compiled code.
```
...
"/apps":
x-router-controller: apps.js
...
```

**Comment by DiV666** [comment]
@jagdish-176 I have tried to do as you suggested but I can't get it to work with ts-node-dev
