### ISSUE TITLE
[Suggestion] Change middleware chain order (Swagger UI not working)

### ISSUE THREAD

**Issue by stevenfukase** [oas-tools/oas-tools#354]
**Is your feature request related to a problem? Please describe.**
Swagger UI path is conflicting with another dynamic path defined in oasFile.
For example, the config
```js
swagger: {
  path: '/docs/swagger/',
},
```
won't work when something like GET `/{segment1}/{segment2}` is defined in oasFile.

**Describe the solution you'd like**
Moving OASSwagger before OASRouter solved the problem.
```js
const middlewareChain = [
  OASParams,
  OASSecurity,
  OASRequestValidator,
  OASResponseValidator,
  OASSwagger,
  OASRouter,
  OASErrorHandler
];
```
instead of the current:
```js
const middlewareChain = [ 
  OASParams, 
  OASSecurity, 
  OASRequestValidator, 
  OASResponseValidator, 
  OASRouter, 
  OASSwagger,
  OASErrorHandler
];
```

Didn't check if this causes other bugs so I'm just submitting this as a suggestion.

**Comment by alesancor1** [comment]
I'm not sure if I understand what the problem is here. You are trying to declare a dynamic route like `/{segment1}/{segment2}` and when calling GET `/docs/swagger` (suppose this is the path where SwaggerUI middleware is registered) you get the response from the router instead of the SwaggerUI right?

Changing the order in the middleware would give priority to the SwaggerUI instead of the router, which may be not desired in some cases.

**Comment by stevenfukase** [comment]
> You are trying to declare a dynamic route like /{segment1}/{segment2} and when calling GET /docs/swagger (suppose this is the path where SwaggerUI middleware is registered) you get the response from the router instead of the SwaggerUI right?

Yes, that's right.

Currently, the only way to show SwaggerUI when dynamic routes are defined is to write a path that does not conflict with the number of the dynamic segment.
That means when `/{dynamic1}/{dynamic2}` is defined in oasFile, the only way to enable swaggerUI is to allocate `/` (with no subdirectory) or `/static1/static2/static3/...` (with 3 or more subdirectories).
`/static1` won't work either.
I just thought it's more intuitive to have the concrete definition (the config) take precedence over dynamic paths.

I have also confirmed that dynamic segments still work even when SwaggerUI is given priority in the middleware chain.
For example, when `/{dynamic1}/{dynamic2}` is defined in oasFile and `/docs/swagger` is allocated for SwaggerUI, GET `/example1/example2` will still work.

**Comment by alesancor1** [comment]
The problem here is that currently you can't call next() on your controllers. The router should be executed before the swaggerUI because you may want to modify `req.swaggerFile` to modify the the swaggerDoc dynamically. In case you had dynamic routes conflicting with the docs route you should manage it on your controllers, since they are responsible for managing requests, for example:

```javascript
// SomeController.js
export function myController(req, res, next) {
    if (/^\/docs(?:\/.*)?$/.test(req.path)) {
         next(); // Calls next middleware (swaggerUI)
    } else {
        /* Manage other requests */
   }
}
```

I think the problem is more related to the ability to solve these conflicts on controllers rather than to the priority of the middleware. I'll take this into account for future versions.

**Comment by stevenfukase** [comment]
I see. Thanks a lot.
