### ISSUE TITLE
express res.json not working with middleware

### ISSUE THREAD

**Issue by jahluwalia** [oas-tools/oas-tools#71]
Hi,

I had a route with the following response:

```
responses:
        "200":
            description: Service is healthy and all dependencies are up
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
```

In swagger-tools, the following line of express code worked. `res.status(200).json(["ok"]);`

But when I look at what's being sent to your middleware, I see that it's getting the string "[\"ok\"]" as opposed to the object ["ok"]

Is this a problem on your side? The express side? Am i not allowed to use res.json()? Any guidance would be much appreciated.

Thanks,
Jas

**Comment by davegrix** [comment]
Try this instead

`res.sendStatus(200).send(JSON.parse("["ok"]")`

or more simply

`res.send(JSON.parse("["ok"]")`

**Comment by yitzgold** [comment]
@davegrix I assume that for now, people can add the following middleware to get around this. Any reason that this would not work?

```
app.use(function(req, res, next) {
  res.json = obj => {
    res.send(JSON.parse(JSON.stringify(obj)));
  };
  next();
});
oasTools.configure(options);

oasTools.initialize(spec, app, function() {

}
```

**Comment by raffrearaUS** [comment]
It seems that using `res.json` runs an additional `JSON.stringify`, which is causing this problem as oas-tools doesn't expect that to happen. I have tried to solve the issue in a number of ways, but none of them appear to work in all possible cases. I will be focusing my attention on this issue as it is currently the oldest open one.

For the time being, you can use `res.send` as suggested in the previous comment.

**Comment by tswaters** [comment]
I was just burned by this - it took me entirely too long to figure out why calling `res.json` was returning a string to the caller - sure enough, oas-tools is getting in the way.

Usually the best thing to do is cases like this is to not do anything at all.

This routine already pulls out `oldSend` and the intention of the routine is to check if the response is correct - if strict mode = on, return an error instead; if strict mode = off, warn the logs.

In my eyes, the reason this is failing is because `content` is mutated in this routine:

https://github.com/isa-group/oas-tools/blob/2.1.7/src/middleware/oas-router.js#L87
https://github.com/isa-group/oas-tools/blob/2.1.7/src/middleware/oas-router.js#L147

Don't do that!!!  

When oldSend is called, the param it is called with should be __identical__ to what it was originally called with.  [or, completely disregarded in lieu of an error when `strict: true`].

**Comment by sageguy09** [comment]
Any timeline for a resolution?

**Comment by vovagalchenko** [comment]
I seem to be running into the same issue with using res.json. @alesancor1: could you clarify why you closed this issue as completed?

**Comment by mikelax** [comment]
I also just ran into this issue using `@oas-tools/core` `3.1.0` and `express` `4.18.2`.
